### ISSUE TITLE
Error with editable install (enabled via presence of setup.cfg): ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm-pep517#46] opened 2021-09-23 11:56 UTC
Given a pyproject.toml like this:
```toml
[project]
name = "myproject"
version = ""
description = ""
authors = [
    {name = "Foo bar", email = "foo@example.com"},
]
dependencies = []
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

And an empty `setup.cfg` file (or one containing only setup for (generic) tools).

Running `pip install -e .` fails:
```
Obtaining file://…/Vcs/pdm/test-editable
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: myproject
  Running setup.py develop for myproject
    ERROR: Command errored out with exit status 1:
     command: …/Vcs/pdm/test-editable/test-venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'…/Vcs/pdm/test-editable/setup.py'"'"'; __file__='"'"'…/Vcs/pdm/test-editable/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: …/Vcs/pdm/test-editable/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: …/Vcs/pdm/test-editable/test-venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'…/Vcs/pdm/test-editable/setup.py'"'"'; __file__='"'"'…/Vcs/pdm/test-editable/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
(the code appears to be from pdm-pep517 (https://github.com/pdm-project/pdm-pep517/blob/master/pdm/pep517/base.py), and it does not fail when not using a build-system section in pyproject.toml (installing it as "UNKNOWN" then))

Note that `pip install .` also fails:
```
Processing /home/user/Vcs/pdm/test-editable
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: myproject
  Building wheel for myproject (PEP 517) ... done
  Created wheel for myproject: filename=myproject--py3-none-any.whl size=854 sha256=66ef6a33ad94bda6b4957a6c418d876b4368beae598138d293bc0760350ab17d
  Stored in directory: /home/user/.cache/pip/wheels/70/04/a4/930f2de3c1b0ee34262a6e0bd34a225d359bc7601504de17c6
  WARNING: Built wheel for myproject is invalid: Wheel has unexpected file name: expected 'UNKNOWN', got ''
Failed to build myproject
ERROR: Could not build wheels for myproject which use PEP 517 and cannot be installed directly
```

Note that the non-editable install also fails without a `setup.cfg`.

pip 21.2.4

**Comment by blueyed** [comment] 2021-09-23 12:18
Adding "setuptools" to `build-system.requires` fixes it.

**Comment by blueyed** [comment] 2021-09-23 15:34
I've come along https://github.com/pdm-project/pdm-pep517/issues/43, and wondered if it is meant for the "path" method to fallback to using setuptools to write .pth files?

The problem I am facing is that `pip install -e .` appears to do nothing when not having `metadata.name` and `options.package_dir = =src` defined in `setup.cfg` (or using a setup.py with specific options for a namespace package using a src layout).

It would be great if the `pdm.pep517.api` backend would handle this based on the options it knows (in particular `tool.pdm.package-dir = "src"`).

**Comment by frostming** [comment] 2021-09-24 01:11
`pip install -e` sets up an **isolated** environment, with only build-requires specified in `pyproject.toml`. It has nothing to do with pdm pep517 backend or anything around that. You can try a flit-backed project and try `pip install -e` and you will find the error is exactly the same.

Not a bug with pdm, close it now.

**Closed by frostming** 2021-09-24 01:11 UTC
